### ISSUE TITLE
please update bitflixapp

### ISSUE THREAD

**Issue by madrid2022ok** [bitflix-official/Bitflix#28]
please when you are going to see improvements and changes we are 2022 and update

**Comment by nuzzesick** [comment]
Hello! I'm not currently working on Bitflix anymore. What kind of improvements/changes do you want to see? Our app is completely open source, you could open a new Pull request any time you want and I will try to review it! 😄

**Comment by madrid2022ok** [comment]
I can't watch series and movies when I play it and it stays loading on bitflixapp

**Comment by nuzzesick** [comment]
Our backend API to support movies/tv shows video streaming is currently has been shutdown. I didn't try to restart the server in any other service because of piracy issues I could have in future.

**Comment by madrid2022ok** [comment]
![7EA80DB9-1B54-42DB-B9CF-DC468BBFE18E](https://user-images.githubusercontent.com/105641464/173255042-756329f0-90c0-45b5-859f-9df44dad7c7c.jpeg)


it stays loading now the movies and series come out that are not available

**Comment by madrid2022ok** [comment]
OK friend

**Comment by madrid2022ok** [comment]
Hello
