### ISSUE TITLE
Streaming cards missing

### ISSUE THREAD

**Issue by JuanPabloDiaz** [bitflix-official/Bitflix#44]
I didnt know what this boxes were until I saw the picture on the readme page.

### Current view
![image](https://github.com/bitflix-official/Bitflix/assets/25883220/3b3b3d29-c0a5-4561-b757-07c60ac89264)

### How they should look like
![image](https://github.com/bitflix-official/Bitflix/assets/25883220/695adbf8-5ea5-4a26-a69d-5b0a1397ae64)

**Comment by nuzzesick** [comment]
fixed. I just had to renew my supabase DB.
